fexp:
	mkdir -p out
	gcc -o out/fexp fexp.c
	out/fexp 2 4

fact:
	mkdir -p out
	gcc -o out/fact fact.c
	out/fact 199429

tau:
	mkdir -p out
	gcc -o out/tau tau.c
	out/tau 199429

isprim:
	mkdir -p out
	gcc -o out/isprim isprim.c
	out/isprim 199429

carmichael:
	mkdir -p out
	gcc -o out/carmichael carmichael.c
	out/carmichael -r 560 570

sieve:
	mkdir -p out
	gcc -o out/sieve sieve.c
	out/sieve -q 100

gcd:
	mkdir -p out
	gcc -o out/gcd gcd.c
	out/gcd 4 6