all:
	- mkdir -p out
	- gcc -o out/main -lm -O2 -pipe -ansi -DONLINE_JUDGE main.c
	- out/main < input.txt

main2:
	- mkdir -p out
	- gcc -o out/main2 -lm -O2 -pipe -ansi -DONLINE_JUDGE main2.c
	- out/main2 < input.txt

playground:
	- mkdir -p out
	- gcc -o out/playground -lm -O2 -pipe -ansi -DONLINE_JUDGE playground.c
	- out/playground < input.txt