all:
	mkdir -p out
	gcc -o out/main -lm -O2 -pipe -ansi -DONLINE_JUDGE main.c
	out/main < input.txt

main3:
	mkdir -p out
	g++ -o out/main3 main3.c
	out/main3 < input.txt

main4:
	mkdir -p out
	gcc -o out/main4 -lm -O2 -pipe -ansi -DONLINE_JUDGE main4.c
	out/main4 < input.txt

main5:
	mkdir -p out
	gcc -o out/main5 -lm -O2 -pipe -ansi -DONLINE_JUDGE main5.c
	out/main5 < input.txt