fexp:
	mkdir -p out
	gcc -o out/fexp fexp.c
	out/fexp 2 4

fact:
	mkdir -p out
	gcc -o out/fact fact.c
	out/fact 199429

tau:
	mkdir -p out
	gcc -o out/tau tau.c
	out/tau 199429

isprim:
	mkdir -p out
	gcc -o out/isprim isprim.c
	out/isprim 199429