all:
	mkdir -p out
	gcc -o out/main -lm -O2 -pipe -ansi -DONLINE_JUDGE main.c
	out/main < input.txt

main2:
	mkdir -p out
	gcc -o out/main2 -lm -O2 -pipe -ansi -DONLINE_JUDGE main2.c
	out/main2 < input.txt

main3:
	mkdir -p out
	gcc -o out/main3 -lm -O2 -pipe -ansi -DONLINE_JUDGE main3.c
	out/main3 < input.txt

uva:
	mkdir -p out
	gcc -o out/main_uva -lm -O2 -pipe -ansi -DONLINE_JUDGE main_uva.c
	out/main_uva < input.txt