all:
	mkdir -p out
	gcc -o out/main main.c
	out/main < input.txt

main2:
	mkdir -p out
	gcc -o out/main2 main2.c
	out/main2 < input.txt

uva:
	mkdir -p out
	gcc -o out/main_uva main_uva.c
	out/main_uva < input.txt