all:
	mkdir -p out
	g++ -o out/main main.cpp -lm -O2 -std=c++11 -pipe -DONLINE_JUDGE
	out/main < input.txt

main2:
	mkdir -p out
	g++ -o out/main2 main2.cpp -lm -O2 -std=c++11 -pipe -DONLINE_JUDGE
	out/main2 < input.txt

main3:
	mkdir -p out
	g++ -o out/main3 main3.c
	out/main3 < input2.txt