all:
	mkdir -p out
	g++ -o out/main main.cpp -lm -O2 -std=c++11 -pipe -DONLINE_JUDGE
	out/main < input.txt

main2:
	mkdir -p out
	g++ -o out/main2 main2.cpp -lm -O2 -std=c++11 -pipe -DONLINE_JUDGE
	out/main2 < input.txt

main3:
	mkdir -p out
	gcc -o out/main3 -lm -O2 -pipe -ansi -DONLINE_JUDGE main3.c
	out/main3 < input.txt

main4:
	mkdir -p out
	gcc -o out/main4 -lm -O2 -pipe -ansi -DONLINE_JUDGE main4.c
	out/main4 < input.txt